require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe UsersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # User. As you add validations to User, be sure to
  # adjust the attributes here as well.
  include_context "fixtures"
  let(:valid_attributes) {
    {name: "Valid User", email: "valid@gmail.com", password: "password", birthdate: "1993-06-18"}
  }

  let(:invalid_attributes) {
    {name: "", email: "invalid", password: "foo", birthdate: nil}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UsersController. Be sure to keep this updated too.
  let(:logged_out_session) { {user_id: nil} }
  let(:logged_in_session) { {user_id: user.id} }
  let(:admin_session) { {user_id: admin.id}}
  

  describe "GET #index" do
    it "returns a success response for admin" do
      get :index, params: {}, session: admin_session
      expect(response).to be_successful
    end

    it "redirects logged in non-admin users to their own show page" do
      get :index, params: {}, session: logged_in_session
      expect(response).to redirect_to(user)
    end

    it "redirects logged out users to home page" do
      get :index, params: {}, session: logged_out_session
      expect(response).to redirect_to(root_path)
    end
  end

  describe "GET #show" do
    it "returns a success response for admin" do
      get :show, params: {id: user.to_param}, session: admin_session
      expect(response).to be_successful
    end

    it "returns a success response for user viewing their own page" do
      get :show, params: {id: user.to_param}, session: logged_in_session
      expect(response).to be_successful
    end

    it "redirects user attempting to view other user back to their own show page" do
      get :show, params: {id: admin.to_param}, session: logged_in_session
      expect(response).to redirect_to(user)
    end

    it "redirects logged out user to home page" do
      get :show, params: {id: user.to_param}, session: logged_out_session
      expect(response).to redirect_to(root_path)
    end
  end

  describe "GET #new" do
    it "returns a success response for logged out user" do
      get :new, params: {}, session: logged_out_session
      expect(response).to be_successful
    end

    it "redirects logged in user to their own show page" do
      get :new, params: {}, session: logged_in_session
      expect(response).to redirect_to(user)
      get :new, params: {}, session: admin_session
      expect(response).to redirect_to(admin)
    end

  end

  describe "GET #edit" do
    it "returns a success response for admin" do
      get :edit, params: {id: user.to_param}, session: admin_session
      expect(response).to be_successful
    end

    it "returns a success response for user editing themself" do
      get :edit, params: {id: user.to_param}, session: logged_in_session
      expect(response).to be_successful
    end

    it "redirects user attempting to edit another user back to their own edit page" do
      get :edit, params: {id: admin.to_param}, session: logged_in_session
      expect(response).to redirect_to(user)
    end

    it "redirects logged out user to home page" do
      get :edit, params: {id: user.to_param}, session: logged_out_session
      expect(response).to redirect_to(root_path)
    end
  end

  describe "POST #create" do
    context "with logged in user" do
      it "redirects to user's show page" do
        post :create, params: {user: valid_attributes}, session: logged_in_session
        expect(response).to redirect_to(user)
      end
    end

    context "with valid params" do
      it "creates a new User" do
        expect {
          post :create, params: {user: valid_attributes}, session: logged_out_session
        }.to change(User, :count).by(1)
      end

      it "automatically sets admin to false" do
        post :create, params: {user: valid_attributes}, session: logged_out_session
        expect(User.last.admin).to be(false)
      end

      it "redirects to the created user" do
        post :create, params: {user: valid_attributes}, session: logged_out_session
        expect(response).to redirect_to(User.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {user: invalid_attributes}, session: logged_out_session
        expect(response).to render_template(:new)
      end
    end
  end

  describe "PATCH #update" do
    
    context "with valid params" do
      let(:new_attributes) { 
        {name: "New Name", birthdate: "2010-01-01", password: "password"}
      }

      it "allows user to update themself" do
        patch :update, params: {id: user.to_param, user: new_attributes}, session: logged_in_session
        user.reload
        expect(response).to redirect_to(user)
        expect(user.name).to eq("New Name")
        expect(user.birthdate).to eq("20100101".to_date)
      end

      it "allows admin to update any user" do
        patch :update, params: {id: user.to_param, user: new_attributes}, session: admin_session
        user.reload
        expect(response).to redirect_to(user)
        expect(user.name).to eq("New Name")
        expect(user.birthdate).to eq("20100101".to_date)
      end

      it "does not allow non-admin to update users other than themself" do
        patch :update, params: {id: admin.to_param, user: new_attributes}, session: logged_in_session
        user.reload
        expect(response).to redirect_to(user)
        expect(user.name).to eq("John Doe")
      end

      it "redirects logged out user to home page" do
        patch :update, params: {id: user.to_param, user: new_attributes}, session: logged_out_session
        expect(response).to redirect_to(root_path)
        expect(user.name).to eq("John Doe")
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        patch :update, params: {id: user.to_param, user: invalid_attributes}, session: logged_in_session
        expect(response).to render_template(:edit)
      end
    end
  end

  describe "DELETE #destroy" do
    it "allows user to delete themself" do
      delete :destroy, params: {id: user.to_param}, session: logged_in_session
      expect(session[:user_id]).to be_nil
      expect(User.all).not_to include(user)
      expect(response).to redirect_to(root_path)
    end

    it "allows admin to delete any user" do
      delete :destroy, params: {id: user.to_param}, session: admin_session
      expect(session[:user_id]).to eq(admin.id)
      expect(User.all).not_to include(user)
      expect(response).to redirect_to(users_path)
    end

    it "does not allow non-admin to delete another users account" do
      delete :destroy, params: {id: admin.to_param}, session: logged_in_session
      expect(session[:user_id]).to eq(user.id)
      expect(User.all).to include(admin)
      expect(response).to redirect_to(user)
    end

    it "does not allow logged out user to delete any user" do 
      delete :destroy, params: {id: user.to_param}, session: logged_out_session
      expect(User.all).to include(user)
      expect(response).to redirect_to(root_path)
    end

  end

end
